title: Restrict Devices
description: Documentation and guides for managing device usage.
url: "https://restrictdevices.com"
baseurl: "/docs" # the subpath of your site, e.g. /blog
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

destination: docs
