remote_theme: eecs485staff/primer-spec

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jemoji

kramdown:
  input: GFM


readme_index:
  remove_originals: true
  with_frontmatter: true


title: "Home"
description: Learn how to block any content on any device for yourself or others.
google_analytics: "G-0HM5HER0XN"
favicon: "/favicon.ico"

primerSpec:
  disableJokes: true
  sitemap:
    label: "Sitemap"